resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: source
    type: pull-request
    source:
      access_token: ((github-access-token))
      private_key: ((github-key))
      repo: ((github-repo))
      uri: ((github-uri))
      version: every

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - put: source
        params:
          context: $BUILD_JOB_NAME
          path: source
          status: pending
      - aggregate:
        - task: run lint rules
          file: source/ci/tasks/run_lint.yml
        - task: run unit tests
          file: source/ci/tasks/run_tests.yml
        on_failure:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: failure
        on_success:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: success

  - name: deploy
    plan:
      - get: source
        trigger: true
        passed: [test]
      - put: source
        params:
          context: $BUILD_JOB_NAME
          path: source
          status: pending
      - task: run build
        file: source/ci/tasks/run_build.yml
        params:
          APP_NAME: ((app-name))
          AUTH_AUDIENCE: ((stage-auth-audience))
          AUTH_DOMAIN: ((stage-auth-domain))
          MIXPANEL_TOKEN: ((stage-mixpanel-token))
          NODE_ENV: 'production'
          STORAGE_BUCKET: ((dev-bucket))
      - task: run deploy
        file: source/ci/tasks/run_deploy.yml
        params:
          APP_NAME: ((app-name))
          GCP_PROJECT: ((dev-gcs-project))
          GCP_SERVICE_ACCOUNT_KEY: ((dev-gcs-token))
          STORAGE_BUCKET: ((dev-bucket))
        on_failure:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: failure
        on_success:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: success

  - name: automate
    plan:
      - get: source
        trigger: true
        passed: [deploy]
      - put: source
        params:
          context: $BUILD_JOB_NAME
          path: source
          status: pending
      - task: run automation on pr
        file: source/ci/tasks/run_automation.yml
        params:
          STORAGE_BUCKET: ((dev-bucket))
          AUTH_AUDIENCE: ((auth-audience))
          AT_IGNORE_CERT_ERRORS: true,
          AT_LOGIN_PASSWORD: ((at-login-password))
          AT_LOGIN_USERNAME: ((at-login-username))
          AT_RUN_IN_BACKGROUND: true
          AUTH_DOMAIN: ((stage-auth-domain))
          REPO: ((github-uri))
        on_failure:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: failure
        on_success:
          put: source
          params:
            context: $BUILD_JOB_NAME
            path: source
            status: success
